### ISSUE TITLE
generate x509 cert

### ISSUE THREAD

**Issue by ITmustang** [MobSF/CapFuzz#3]
great tool! would it be possible to generate an x509 cert. heres why..
app im testing is cert pinning. ive bypassed it with burpsuite cert using the method and script here..
https://blog.it-securityguard.com/the-stony-path-of-android-%F0%9F%A4%96-bug-bounty-bypassing-certificate-pinning/ 
but when i attempt the same with any of the certs for capfuzz, i get this error... (which seems to be bc its not an x509 cert.) 
Error: java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0c0890ba:ASN.1 encoding routines:asn1_check_tlen:WRONG_TAG
    at frida/node_modules/frida-java/lib/env.js:218
    at input:1
    at [anon] (/repl1.js:35)
    at frida/node_modules/frida-java/lib/vm.js:39
    at v (frida/node_modules/frida-java/index.js:344)
    at frida/node_modules/frida-java/index.js:315
    at frida/node_modules/frida-java/lib/vm.js:39
    at /_java.js:2384
    at [anon] (/repl1.js:63)

**Comment by ajinabraham** [comment]
These are x.509 certs
https://github.com/MobSF/CapFuzz/tree/master/capfuzz/ca
https://support.ssl.com/Knowledgebase/Article/View/19/0/der-vs-crt-vs-cer-vs-pem-certificates-and-how-to-convert-them
