### ISSUE TITLE
Dynamic Analysis Error! Clientdisconnect

### ISSUE THREAD

**Issue by zym-wade** [MobSF/CapFuzz#6]
I start the dynamic analysis and configured on a real android device the MobSF proxy Capfuz. When I start downloading data using some app, the output of python3 manage.py runserver contains hundreds of lines:
`some-ip:port: clientconnect
some-ip:port clientdisconnect
```
`

I fear to miss out important messages because of that.

**Comment by zym-wade** [comment]
`some-ip:port: clientconnect
some-ip:port clientdisconnect`

**Comment by ajinabraham** [comment]
This is generated by MITM Proxy. Not sure if we can disable them. Again there is nothing critical happening in the console log. The important info will be logged to MobSF log file.
